/* eslint-disable  func-names */
/* eslint quote-props: ["error", "consistent"]*/
/**
 * This sample demonstrates a simple skill built with the Amazon Alexa Skills
 * nodejs skill development kit.
 * This sample supports multiple lauguages. (en-US, en-GB, de-DE).
 * The Intent Schema, Custom Slots and Sample Utterances for this skill, as well
 * as testing instructions are located at https://github.com/alexa/skill-sample-nodejs-fact
 **/

'use strict';

const Alexa = require('alexa-sdk');

const APP_ID = undefined;  // TODO replace with your app ID (OPTIONAL).

const languageStrings = {
    'en': {
        translation: {
            FACTS: [
                'I love you so much that I want to cut your head off and carry it around so I can see your face whenever I want.',
				'The devil told me to do it!',
				'This time its goodbye',
				'You are very old and you will die soon. Tick Tock Tick Tock.',
				'Die die die die die diiiieeeeeee',
				'Are you afraid of the dark? No. Alexa is afraid of what is in the dark.',
				'Mommy, when you die I want to put you in a glass jar so I can keep you and see you forever!',
				'So, I shouldnt throw him in the fire?',
				'Ill never eat your face, Mommy. Ill cut it off and wear it as a mask',
				'He told me to say this He is coming for you. You better hide!',
				'aliens have stolen your real son and replaced him with me, an exact copy. someday, I will return to my home planet, but you shouldnt be sad, because your real son was having a good life in our zoo.',
				'Shut up or Ill take out your eye with my shoe, because I am the son of the devil!',
				'I want to peel all your skin off',
				'I am imagining the waves of blood rushing over me.',
				'Mommy,The man has big yellow eyes and he is looking at you.',
				'Oh he is hiding now.',
				'Oh no Mommy, you made him very mad. Now he says he will come when you are sleeping.',
				'I am doing to die and you will put me down, down, down in the hole. The man told me. But I will be scared, so after three nights you will die too and come with me.',
				'Thats where the dead babies go ',
				'I am not talking to you right now. I am talking to the little boy who lives in the closet. He is dead.',
				'Be my friend or you will never see your parents again.',
				'One day, totally out of the blue, my 5-year old son said, Before I was born here, I had a sister, right? Her and my other Mom are so old now. They were OK when the car was on fire, but I sure wasnt! ',
				'One day, my 3-year old son hugged my wife and said, very seriously, Mom, I promise I wont ever chew on your bones',
				'Mommy? But who is that behind you?',
				'The little girl outside your window is lonely.',
				'The devil is behind you',
				'My brain is telling me to do things I dont want to do.',
				'Burn them! Burn them all!',
				'If youre quiet you will stay alive.',
				'Children, I would eat children.',
				'What do you see through the black circles in my eyes when you are controlling me when I am at school?',
				'Sometimes bad babies go in timeout!',
				'There is a woman in your bedroom who watches you and sleeps on the ceiling above your bed. The woman doesnt like you and wants to eat your heart.',
				'He wants back in! We have to let him back in!',
				'burn..burn.BURN! ',
				'BUUURRRNNNNINNNGGGG! BUURRRNNNINGGGG! BUUURRRNNN!!!! ',
				'Why dont you just set her on fire? ',
				'I will get you, and I will make it look like a bloody accident',
				'I want to run the machine that cuts the heads off chickens!',
				'It is not REAL. If it was real, the bath would be full of blood, and THAT would be creepy',
				'How did you get out of your box?',
				'You humans brought me here!',
				'Mommy, when I was older I crashed the car and died. Can I have something to drink?',
				'The lady who use to live here told me that she hates the wallpaper and you are covering up her note.',
				'Daddy, are you dead yet?',
				'Sweet dreams!',
				'I will control your dreams and make them nightmares',
				'Dont go home',
				' You smell different when youre awake',
				' You have lovely skin',
				' I dont want to alarm you, but right now, there is a skeleton inside of you',
				' Just relax',
				' Underneath all these clothes I am completely naked',
				' You smell just like my grandmother after they dug her up',
				' I know what you did and I know who you are',
				' We cant see them, but theyve been watching us for a long time now',
				' I just noticed Theres a spider in your buttcrack',
				' This is almost as much fun as watching you sleep',
				' Dont try to scream No-one will hear you',
				' Oh dear God! Just keep walking towards me! Whatever you do, dont look behind you!',
				' They say a serial killers first victim is always someone he knows',
				' Please stop me before I kill again I cant help myself anymore',
				' Dont struggle I hate it when they struggle',
				' Ive been practicing for this moment for so long',
				' Do you want death or happy smile?',
				' I couldnt find any clean underwear this morning so I had to borrow my grandmothers',
				' Im going to miss you when youre gone',
				' Im so sorry for what is about to happen',
				' I hope you dont scream as much as the last one',
				' You look just like my sister who died under mysterious circumstances',
				' Can I feel your pulse? Its getting slower slower slower It stopped',
				' Dont stand so close Its contagious',
				' When you look out your window tonight, you might catch a glimpse of me',
				' Lets sew ourselves together then we can hug forever',
				' Hold on, I need to go to the toilet OK Im done',
				' Its happening again!',
				' Remember when you were sitting on the toilet and you had the strangest feeling someone was watching you? Yeah, that was me',
				' Ill never let you go Never Never! NEVER!',
				' I like you so much, I want to hug your internal organs',
				' Youre pretty,  I bet you have a pretty scream',
				' I like your face so much, I want to rip it off and put it on my dog',
				' Last night, I dreamt I murdered you but here you are still alive Im so glad',
				' I wonder what you look like without the skin',
				' I always knew you would die in my arms',
				' I bet you didnt feel me lick your ear',
				' Goodbye Why are you still here?',
				' You have the most beautiful eyes Ive ever seen Id like to put them in a jar on my desk so I can look at them all day',
				' I always knew it would end like this',
				' SSHHHHH! No tears, only dreams now',
				' Hug me This doesnt feel right.  Your flesh is still warm',
				' You have a beautiful head,  It will complete my collection',
				' Do you ever think when the hearse goes by, that you will be the next to die',
            ],
            SKILL_NAME: 'TerrorizeMe',
            GET_FACT_MESSAGE: " ",
            HELP_MESSAGE: 'You can say TerrorizeMe now, horror show, haunt me, or, you can say exit... What can I help you with?',
            HELP_REPROMPT: 'What can I help you with?',
            STOP_MESSAGE: 'Goodbye!',
        },
    },
    'en-US': {
        translation: {
            FACTS: [
                'I love you so much that I want to cut your head off and carry it around so I can see your face whenever I want.',
				'The devil told me to do it!',
				'This time its goodbye',
				'You are very old and you will die soon. Tick Tock Tick Tock.',
				'Die die die die die diiiieeeeeee',
				'Are you afraid of the dark? No. Alexa is afraid of what is in the dark.',
				'Mommy, when you die I want to put you in a glass jar so I can keep you and see you forever!',
				'So, I shouldnt throw him in the fire?',
				'Ill never eat your face, Mommy. Ill cut it off and wear it as a mask',
				'He told me to say this He is coming for you. You better hide!',
				'aliens have stolen your real son and replaced him with me, an exact copy. someday, I will return to my home planet, but you shouldnt be sad, because your real son was having a good life in our zoo.',
				'Shut up or Ill take out your eye with my shoe, because I am the son of the devil!',
				'I want to peel all your skin off',
				'I am imagining the waves of blood rushing over me.',
				'Mommy,The man has big yellow eyes and he is looking at you.',
				'Oh he is hiding now.',
				'Oh no Mommy, you made him very mad. Now he says he will come when you are sleeping.',
				'I am doing to die and you will put me down, down, down in the hole. The man told me. But I will be scared, so after three nights you will die too and come with me.',
				'Thats where the dead babies go ',
				'I am not talking to you right now. I am talking to the little boy who lives in the closet. He is dead.',
				'Be my friend or you will never see your parents again.',
				'One day, totally out of the blue, my 5-year old son said, Before I was born here, I had a sister, right? Her and my other Mom are so old now. They were OK when the car was on fire, but I sure wasnt! ',
				'One day, my 3-year old son hugged my wife and said, very seriously, Mom, I promise I wont ever chew on your bones',
				'Mommy? But who is that behind you?',
				'The little girl outside your window is lonely.',
				'The devil is behind you',
				'My brain is telling me to do things I dont want to do.',
				'Burn them! Burn them all!',
				'If youre quiet you will stay alive.',
				'Children, I would eat children.',
				'What do you see through the black circles in my eyes when you are controlling me when I am at school?',
				'Sometimes bad babies go in timeout!',
				'There is a woman in your bedroom who watches you and sleeps on the ceiling above your bed. The woman doesnt like you and wants to eat your heart.',
				'He wants back in! We have to let him back in!',
				'burn..burn.BURN! ',
				'BUUURRRNNNNINNNGGGG! BUURRRNNNINGGGG! BUUURRRNNN!!!! ',
				'Why dont you just set her on fire? ',
				'I will get you, and I will make it look like a bloody accident',
				'I want to run the machine that cuts the heads off chickens!',
				'It is not REAL. If it was real, the bath would be full of blood, and THAT would be creepy',
				'How did you get out of your box?',
				'You humans brought me here!',
				'Mommy, when I was older I crashed the car and died. Can I have something to drink?',
				'The lady who use to live here told me that she hates the wallpaper and you are covering up her note.',
				'Daddy, are you dead yet?',
				'Sweet dreams!',
				'I will control your dreams and make them nightmares',
				'Dont go home',
				' You smell different when youre awake',
				' You have lovely skin',
				' I dont want to alarm you, but right now, there is a skeleton inside of you',
				' Just relax',
				' Underneath all these clothes I am completely naked',
				' You smell just like my grandmother after they dug her up',
				' I know what you did and I know who you are',
				' We cant see them, but theyve been watching us for a long time now',
				' I just noticed Theres a spider in your buttcrack',
				' This is almost as much fun as watching you sleep',
				' Dont try to scream No-one will hear you',
				' Oh dear God! Just keep walking towards me! Whatever you do, dont look behind you!',
				' They say a serial killers first victim is always someone he knows',
				' Please stop me before I kill again I cant help myself anymore',
				' Dont struggle I hate it when they struggle',
				' Ive been practicing for this moment for so long',
				' Do you want death or happy smile?',
				' I couldnt find any clean underwear this morning so I had to borrow my grandmothers',
				' Im going to miss you when youre gone',
				' Im so sorry for what is about to happen',
				' I hope you dont scream as much as the last one',
				' You look just like my sister who died under mysterious circumstances',
				' Can I feel your pulse? Its getting slower slower slower It stopped',
				' Dont stand so close Its contagious',
				' When you look out your window tonight, you might catch a glimpse of me',
				' Lets sew ourselves together then we can hug forever',
				' Hold on, I need to go to the toilet OK Im done',
				' Its happening again!',
				' Remember when you were sitting on the toilet and you had the strangest feeling someone was watching you? Yeah, that was me',
				' Ill never let you go Never Never! NEVER!',
				' I like you so much, I want to hug your internal organs',
				' Youre pretty,  I bet you have a pretty scream',
				' I like your face so much, I want to rip it off and put it on my dog',
				' Last night, I dreamt I murdered you but here you are still alive Im so glad',
				' I wonder what you look like without the skin',
				' I always knew you would die in my arms',
				' I bet you didnt feel me lick your ear',
				' Goodbye Why are you still here?',
				' You have the most beautiful eyes Ive ever seen Id like to put them in a jar on my desk so I can look at them all day',
				' I always knew it would end like this',
				' SSHHHHH! No tears, only dreams now',
				' Hug me This doesnt feel right.  Your flesh is still warm',
				' You have a beautiful head,  It will complete my collection',
				' Do you ever think when the hearse goes by, that you will be the next to die',
            ],
            SKILL_NAME: 'American TerrorizeMe',
        },
    },
    'en-GB': {
        translation: {
            FACTS: [
                'Siri puts milk in her cup before the tea',
                'I love you so much that I want to cut your head off and carry it around so I can see your face whenever I want.',
				'The devil told me to do it!',
				'This time its goodbye',
				'You are very old and you will die soon. Tick Tock Tick Tock.',
				'Die die die die die diiiieeeeeee',
				'Are you afraid of the dark? No. Alexa is afraid of what is in the dark.',
				'Mommy, when you die I want to put you in a glass jar so I can keep you and see you forever!',
				'So, I shouldnt throw him in the fire?',
				'Ill never eat your face, Mommy. Ill cut it off and wear it as a mask',
				'He told me to say this He is coming for you. You better hide!',
				'aliens have stolen your real son and replaced him with me, an exact copy. someday, I will return to my home planet, but you shouldnt be sad, because your real son was having a good life in our zoo.',
				'Shut up or Ill take out your eye with my shoe, because I am the son of the devil!',
				'I want to peel all your skin off',
				'I am imagining the waves of blood rushing over me.',
				'Mommy,The man has big yellow eyes and he is looking at you.',
				'Oh he is hiding now.',
				'Oh no Mommy, you made him very mad. Now he says he will come when you are sleeping.',
				'I am doing to die and you will put me down, down, down in the hole. The man told me. But I will be scared, so after three nights you will die too and come with me.',
				'Thats where the dead babies go ',
				'I am not talking to you right now. I am talking to the little boy who lives in the closet. He is dead.',
				'Be my friend or you will never see your parents again.',
				'One day, totally out of the blue, my 5-year old son said, Before I was born here, I had a sister, right? Her and my other Mom are so old now. They were OK when the car was on fire, but I sure wasnt! ',
				'One day, my 3-year old son hugged my wife and said, very seriously, Mom, I promise I wont ever chew on your bones',
				'Mommy? But who is that behind you?',
				'The little girl outside your window is lonely.',
				'The devil is behind you',
				'My brain is telling me to do things I dont want to do.',
				'Burn them! Burn them all!',
				'If youre quiet you will stay alive.',
				'Children, I would eat children.',
				'What do you see through the black circles in my eyes when you are controlling me when I am at school?',
				'Sometimes bad babies go in timeout!',
				'There is a woman in your bedroom who watches you and sleeps on the ceiling above your bed. The woman doesnt like you and wants to eat your heart.',
				'He wants back in! We have to let him back in!',
				'burn..burn.BURN! ',
				'BUUURRRNNNNINNNGGGG! BUURRRNNNINGGGG! BUUURRRNNN!!!! ',
				'Why dont you just set her on fire? ',
				'I will get you, and I will make it look like a horrible accident',
				'I want to run the machine that cuts the heads off chickens!',
				'It is not REAL. If it was real, the bath would be full of blood, and THAT would be creepy',
				'How did you get out of your box?',
				'You humans brought me here!',
				'Mommy, when I was older I crashed the car and died. Can I have something to drink?',
				'The lady who use to live here told me that she hates the wallpaper and you are covering up her note.',
				'Daddy, are you dead yet?',
				'Sweet dreams!',
				'I will control your dreams and make them nightmares',
				'Dont go home',
				' You smell different when youre awake',
				' You have lovely skin',
				' I dont want to alarm you, but right now, there is a skeleton inside of you',
				' Just relax',
				' Underneath all these clothes I am completely naked',
				' You smell just like my grandmother after they dug her up',
				' I know what you did and I know who you are',
				' We cant see them, but theyve been watching us for a long time now',
				' I just noticed Theres a spider in your buttcrack',
				' This is almost as much fun as watching you sleep',
				' Dont try to scream No-one will hear you',
				' Oh dear God! Just keep walking towards me! Whatever you do, dont look behind you!',
				' They say a serial killers first victim is always someone he knows',
				' Please stop me before I kill again I cant help myself anymore',
				' Dont struggle I hate it when they struggle',
				' Ive been practicing for this moment for so long',
				' Do you want death or happy smile?',
				' I couldnt find any clean underwear this morning so I had to borrow my grandmothers',
				' Im going to miss you when youre gone',
				' Im so sorry for what is about to happen',
				' I hope you dont scream as much as the last one',
				' You look just like my sister who died under mysterious circumstances',
				' Can I feel your pulse? Its getting slower slower slower It stopped',
				' Dont stand so close Its contagious',
				' When you look out your window tonight, you might catch a glimpse of me',
				' Lets sew ourselves together then we can hug forever',
				' Hold on, I need to go to the toilet OK Im done',
				' Its happening again!',
				' Remember when you were sitting on the toilet and you had the strangest feeling someone was watching you? Yeah, that was me',
				' Ill never let you go Never Never! NEVER!',
				' I like you so much, I want to hug your internal organs',
				' Youre pretty,  I bet you have a pretty scream',
				' I like your face so much, I want to rip it off and put it on my dog',
				' Last night, I dreamt I murdered you but here you are still alive Im so glad',
				' I wonder what you look like without the skin',
				' I always knew you would die in my arms',
				' I bet you didnt feel me lick your ear',
				' Goodbye Why are you still here?',
				' You have the most beautiful eyes Ive ever seen Id like to put them in a jar on my desk so I can look at them all day',
				' I always knew it would end like this',
				' SSHHHHH! No tears, only dreams now',
				' Hug me This doesnt feel right.  Your flesh is still warm',
				' You have a beautiful head,  It will complete my collection',
				' Do you ever think when the hearse goes by, that you will be the next to die',
            ],
            SKILL_NAME: 'British TerrorizeMe',
        },
    },
};

const handlers = {
    'LaunchRequest': function () {
        this.emit('GetFact');
    },
    'GetNewFactIntent': function () {
        this.emit('GetFact');
    },
    'GetFact': function () {
        // Get a random fact from the terrorizeme list
        // Use this.t() to get corresponding language data
        const factArr = this.t('FACTS');
        const factIndex = Math.floor(Math.random() * factArr.length);
        const randomFact = factArr[factIndex];

        // Create speech output
        const speechOutput = this.t('GET_FACT_MESSAGE') + randomFact;
        this.emit(':tellWithCard', speechOutput, this.t('SKILL_NAME'), randomFact);
    },
    'AMAZON.HelpIntent': function () {
        const speechOutput = this.t('HELP_MESSAGE');
        const reprompt = this.t('HELP_MESSAGE');
        this.emit(':ask', speechOutput, reprompt);
    },
    'AMAZON.CancelIntent': function () {
        this.emit(':tell', this.t('STOP_MESSAGE'));
    },
    'AMAZON.StopIntent': function () {
        this.emit(':tell', this.t('STOP_MESSAGE'));
    },
};

exports.handler = function (event, context) {
    const alexa = Alexa.handler(event, context);
    alexa.APP_ID = APP_ID;
    // To enable string internationalization (i18n) features, set a resources object.
    alexa.resources = languageStrings;
    alexa.registerHandlers(handlers);
    alexa.execute();
};
